refactors files to support localization
weareinreach/inreach-catalog pull request #125
Opened 2021-02-14 22:59 UTC by FJKhan

## Description

Refactors the following:
- MoreMobile.js
- AccountMobile.js
- LoginFormContainer.js
- LoginForm.js

- Asana ticket: Related to #117 

## PR Checklist

- [x] Assign @Alfredo-Moreira  as a reviewer.
- [x] If your PR is not a hotfix, is it targeted for `dev`? If it is a hotfix, is it targeted for `master`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [x] Does the original ticket have test instructions? If not add them below

## How to Test

- Launch the app (mobile view)
- Click "More"
   - Verify all sections display correctly
   - Verify all links function correctly
- Click "Account"
   - Verify all sections display correctly
   - Verify all links function correctly

### Regression Checks:
 - Existing user is able to sign in
 - New user is able to sign up
 - Tab toggle between Sign In and Sign Up screens function correctly

2021-02-19 05:52 UTC, Alfredo-Moreira requested changes
Tested with:

- Version 88.0.4324.182 (Official Build) (x86_64)

Tested by:

- Opening Heroku deployment (https://reviews-catalog-pr-125.herokuapp.com/ )
- Right-click and select inspect element
- Switch view to Mobile options

Findings:
- Application crashed. It is unable to load on mobile view mode.
- Application does load in Desktop and iPad format

Conclusion:
- PR has failed QA gate. Requesting changes.

[#125.zip](https://github.com/asylum-connect/asylumconnect-catalog/files/6007915/125.zip)

2021-02-25 17:22 UTC, FJKhan commented
> Tested with:
> 
> * Version 88.0.4324.182 (Official Build) (x86_64)
> 
> Tested by:
> 
> * Opening Heroku deployment (https://reviews-catalog-pr-125.herokuapp.com/ )
> * Right-click and select inspect element
> * Switch view to Mobile options
> 
> Findings:
> 
> * Application crashed. It is unable to load on mobile view mode.
> * Application does load in Desktop and iPad format
> 
> Conclusion:
> 
> * PR has failed QA gate. Requesting changes.
> 
> [#125.zip](https://github.com/asylum-connect/asylumconnect-catalog/files/6007915/125.zip)


very interesting issue here:
the menu links for "favourites" and "account" were incorrect. this led to the application attempting to set the locale with the contents of the menu label (favourites/account). in such a scenario, the application was configured to remove the locale item in local storage which in turn broke the app. I've fixed that and refactored the messages.

2021-02-28 05:49 UTC, Alfredo-Moreira commented
Tested with:

Version 88.0.4324.182 (Official Build) (x86_64)
Tested by:

Opening Heroku deployment (https://reviews-catalog-pr-125.herokuapp.com/ )
Right-click and select inspect element
Switch view to Mobile options
Navigates to Account and More
Switched Language to Mexico, Canada, and US.

Findings:
The application worked correctly.
One Network error when change language. Screenshot attached to the zipped folder.
Conclusion:

PR has passed QA Gate.
[#125 - 2.zip](https://github.com/asylum-connect/asylumconnect-catalog/files/6056302/125.-.2.zip)

2021-02-28 05:50 UTC, Alfredo-Moreira approved these changes

2021-03-02 14:50 UTC, merged