Feature/1200973179398805/signup-flow-new-design
weareinreach/inreach-catalog pull request #185
Opened 2021-12-13 02:28 UTC by trigal2012

## Description

sign up flow redesign - updated the name of the PR to indicate that this is for all of the changes, not just one component

## Asana ticket:
https://app.asana.com/0/1132189118126148/1169561089123233

## PR Checklist

- [ ] Assign @FJKhan **and** @Alfredo-Moreira as reviewers.
- [ ] If your PR is not a hotfix, is it targeted for `dev`? If it is a hotfix, is it targeted for `main`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [ ] Does the original ticket have test instructions? If not add them below
- [ ] Pass QA Gate(manual testing)

## How to Test

2021-12-29 15:31 UTC, FJKhan commented on src/components/NameEmailPswd.js
> +	const handleTouchName = () => {
these handlers aren't necessary. it'd be better to use the hook directly

2021-12-29 15:40 UTC, FJKhan requested changes, later dismissed

2021-12-29 15:40 UTC, FJKhan commented on src/components/NameEmailPswd.js
> +						touchedPassword && pswdTest.test(password) === false ? (
```suggestion
						touchedPassword && !pswdTest.test(password)  ? (
```

2021-12-29 15:40 UTC, FJKhan commented on src/components/NameEmailPswd.js
> +						) : touchedPassword && pswdTest.test(password) === true ? (
```suggestion
						) : touchedPassword && pswdTest.test(password) ? (
```

2021-12-29 15:40 UTC, FJKhan commented on src/components/NameEmailPswd.js
> +					disabled={isValid() === false ? true : false}
```suggestion
					disabled={!isValid()}
```

2021-12-29 15:40 UTC, FJKhan commented on src/components/NameLocationLawyerProvider.js
> +	const handleTouchName = () => {
these handlers aren't necessary. use the hook directly

2021-12-29 15:40 UTC, FJKhan commented on src/components/OrganizationAutocomplete.js
> +				className={
use interpolated string

```suggestion
				className={ `${classes.textFieldLabel} ${classes.textAlignLeft} ${classes.colorGrey}` }
```

2021-12-29 15:40 UTC, FJKhan commented on src/components/SignupFormContainer.js
> +		if (pswdTest.test(password) === false) {
```suggestion
		if (!pswdTest.test(password)) {
```

2021-12-29 15:40 UTC, FJKhan commented on src/components/SignupFormContainer.js
> +		if (emailTest.test(email) === false) {
`test()` returns a boolean. you don't need to compare it, just use the returned value to make assertions.
```suggestion
		if (!emailTest.test(email)) {
```

2021-12-29 15:40 UTC, FJKhan commented on src/data/aboutYouFormOptions.js
> +		formatMessageId: 'aboutyou.ehnicity-answer-af-md'
"ethnicity" is misspelt in all options

```suggestion
		formatMessageId: 'aboutyou.ethnicity-answer-af-md'
```

2021-12-29 15:49 UTC, FJKhan commented
re: data storage -- ideally, we need the plain text responses as the whole point of capturing this data is to generate metrics. while `aboutyou.identity-anser-non-binary` is useful for localization, the data would be harder to parse for those performing analysis.

i.e. instead of `aboutyou.identity-anwser-non-binary`, we'd store "non-binary"


![](https://user-images.githubusercontent.com/10123216/146424985-26d3ebe3-f6d4-4e05-a6bb-e47f7bb04cfb.png)

2022-01-16 21:19 UTC, Alfredo-Moreira approved these changes
Looks Good to me. Nice work!

2022-01-17 03:31 UTC, merged